require("xray")
require('move').setup({})
vim.api.nvim_create_user_command('W', 'w', {})
vim.api.nvim_create_user_command('Wq', 'wq', {})
vim.api.nvim_create_user_command('WQ', 'wq', {})
vim.api.nvim_create_user_command('Q', 'q!', {})
vim.keymap.set('i', '<C-4>', '<Esc>$i', { noremap = true, silent = true })
vim.keymap.set('n', '<C-4>', '<Esc>$', { noremap = true, silent = true })
vim.keymap.set('i', '<C-S>', '<Esc>:wi', { noremap = true, silent = true})
vim.keymap.set('i', '<C-s>', '<Esc>:wi', { noremap = true, silent = true})
vim.keymap.set('n', '<C-S>', '<Esc>:w', { noremap = true, silent = true})
vim.keymap.set('n', '<C-S>', '<Esc>:w', { noremap = true, silent = true})
vim.keymap.set('i', '<C-4>', '<Esc>$i', { noremap = true, silent = true })
vim.keymap.set('n', '<C-4>', '<Esc>$i', { noremap = true, silent = true })

